name: publish-to-github-pages

on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.15.4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install dependencies
        shell: bash
        run: pnpm install

      - name: Setup pages
        uses: actions/configure-pages@v4

      - name: Build with Next.js
        run: pnpm dendron publish export

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./next/out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Publish to GitHub pages
        id: deployment
        uses: actions/deploy-pages@v4
